### ISSUE TITLE
卷扩展

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#14]
一开始设置的卷不够大，如何扩展卷？

**Comment by shenkejie15** [comment]
已部署：

![image](https://user-images.githubusercontent.com/48315992/234245934-3b7b3775-2a88-494b-a296-3285666b9619.png)

目前如果使用 1.1Gi，1200Mi 等数值，实际的 PVC 大小都会被向上取整为 2Gi。

**Comment by tswangdi** [comment]
使用 Ceph 的 PVC 暂时已知有以下特性：

1. 最小分配单位为 4 Mi，即如果设置为 5 Mi，会实际调整为 8 Mi，这是 Ceph 决定的
2. 如果空间大小超过 1 Gi，则当设置的存储空间会被向上取整为整数 Gi，其他单位不会出现此问题。这个应该是 K8s PVC 的一个特性
