### ISSUE TITLE
进程ID不显示

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#24]
不显示具体的 Processes，没法定位自己的程序到底占用了多少资源。

<img width="360" alt="image" src="https://user-images.githubusercontent.com/48315992/226560570-80beffed-770b-40b2-aae9-0a8c3b2172cf.png">

**Comment by quanguachong** [comment]
Build Console 已更新：

当 Job 中的 Pod 使用 nvidia.com/gpu 时， Build Console 的 Job 详情页面可以显示 GPU 显存的使用情况。

但需要注意的是，如果 Pod 使用 nvidia.com/gpu.shared，目前无法显示 GPU 使用情况，因为提供 GPU metrics 的 dcgm exporter 不支持，详情见：https://github.com/NVIDIA/dcgm-exporter/issues/151
