### ISSUE TITLE
同个notebook文件列表显示不相同

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#33]
![img_v2_357c2fad-a642-4d0b-88ce-2ca580cdb09g](https://user-images.githubusercontent.com/34251317/227468040-fb595c48-1c7b-44a7-9f9f-8f3b0803fa4d.png)![img_v2_783928bd-c8a8-4b9b-bcd3-ced02c0af8bg](https://user-images.githubusercontent.com/34251317/227467983-6629fa9a-43e4-49dd-a7e2-1b5bab269a41.png)以上两张图在同一个notebook中。其中左侧文件列表中显示不同。

**Comment by shenkejie15** [comment]
未能复现这个问题。请问这个问题是否仍然存在，能否提供稳定复现的方法？

**Comment by wd0011** [comment]
目前没有再复现过，也没有稳定的复现方案。先关注好了

**Comment by shenkejie15** [comment]
本问题暂时没有复现方案，关闭 issue。
如果遇到了相同的问题，欢迎打开 issue 继续讨论。
