### ISSUE TITLE
项目共享

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#34]
共享项目之后，被共享人的界面无法看到共享内容。需要刷新。

**Comment by tswangdi** [comment]
实时推送对产品的改动加大，优先级比较低。目前实现方式是，前端每十秒会更新一次项目列表。

所以共享项目后，被共享人的界面在 10 秒之内可以看到更新内容。应该已经可以满足使用场景。

Issue 关闭，如果后续还有其他问题，重新打开该 Issue
