### ISSUE TITLE
共享目录挂载

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#38]
单独共享某个pvc，而不共享整个项目。

**Comment by shenkejie15** [comment]
文档更新在：https://t9k.github.io/user-docs/guide/manage-auxiliary-resources/use-pvc-over-s3.html#%E8%AF%A6%E7%BB%86%E8%BF%87%E7%A8%8B

**Comment by shenkejie15** [comment]
问题已得到解答，关闭 issue。
如果您遇到了类似的问题或者有进一步的建议，可以随时重新打开这个 issue。
