### ISSUE TITLE
PVC issues

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#40]
![img_v2_d9793f98-8195-41b8-b43f-c9e605ae145g](https://user-images.githubusercontent.com/34251317/230285503-f63e93a3-843b-4285-931e-04b0da8e7f68.jpg)
PVC的一直在loading打不开，重新打开也没有用。

**Comment by shenkejie15** [comment]
已经部署：

![image](https://user-images.githubusercontent.com/48315992/234240021-0ac4b536-bd9f-48cc-9acd-aada5379f55c.png)
