### ISSUE TITLE
notebook 使用多显卡

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#42]
notebook配置的时候，需要可以选择一张以上的显卡。多张显卡的环境才能用来测试多显卡脚本是否运行正常，是否能提交到job上进行运行。
tips: 最好是申请试用多张显卡的权限需要审批，保证资源不被滥用。

**Comment by xyxxxxx** [comment]
如果是为了测试分布式脚本是否运行正常，我们新增加的 Job 的 debug 模式可以便于用户进行调试，请参阅[使用 Job 的 debug 模式进行调试](https://github.com/t9k/tutorial-examples/tree/master/job/debug-mode)。

Notebook 使用多 GPU 这件事我们也计划支持，目前仍在讨论方案。

**Comment by ppkube** [comment]
> Notebook 使用多 GPU 这件事我们也计划支持，目前仍在讨论方案。

notebook 使用 多 GPU 本身是支持的，只是目前的管理策略只允许 notebook 使用 shared gpu。原因是 notebook 是 交互式环境，大部分时间处于空闲状态，使用独占模式的 GPU 会导致较大的资源浪费；同时， 系统又提供 Job 类型的计算以支持方便、快速的运行多 GPU 的计算任务。

**Comment by shenkejie15** [comment]
问题已得到解答，关闭 issue。
如果您遇到了类似的问题或者有进一步的建议，可以随时重新打开这个 issue。
