### ISSUE TITLE
创建了新的 notebook 后，端口转发到本地终端里找不到 conda?

### ISSUE THREAD

**Issue by Reisen301** [t9k/user-support#46]
浏览器的 JupyterLab 里的终端可以找到
![image](https://user-images.githubusercontent.com/25822863/231926909-4d2757d8-18cc-4065-b6ae-115854f6e169.png)

但端口转发到本地终端无法找到
![image](https://user-images.githubusercontent.com/25822863/231926627-8380b7ba-83b1-4883-8fc6-a1f18b52eccd.png)

旧的 notebook 没有此问题

尝试过的镜像列表：
registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-2.0.0-notebook:1.71.0-sudo
registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-1.13.1-notebook:1.71.0-sudo

**Comment by xyxxxxx** [comment]
新发布的 torch notebook 镜像解决了上述问题，请使用镜像：

* registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-1.13.1-notebook:1.72.0
* registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-2.0.0-notebook:1.72.0

以及对应的 sudo 镜像。 @Reisen301

**Comment by shenkejie15** [comment]
> * registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-1.13.1-notebook:1.72.0
> * registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/torch-2.0.0-notebook:1.72.0

已经设为创建 Notebook 时提供的标准镜像。如果创建时看到的版本不是 1.72.0，请禁用浏览器缓存后刷新页面。

**Comment by shenkejie15** [comment]
问题已解决，关闭 issue。
