### ISSUE TITLE
网页端与ssh端访问同一个notebook存在差异

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#47]
1. 网页端terminal 输入env和在ssh terminal 输入env，显示的环境变量不同。
2. 同个notebook使用同一个conda环境，网页端terminal和ssh terminal读取到的conda list不同。
![img_v2_d050dc6e-4b2f-4eb1-87db-6eb04ef9c1dg](https://user-images.githubusercontent.com/34251317/231991167-c86bd471-10c6-4a60-89f1-8e74b6ef0625.png)
tips: 图中1.txt是网页端terminal得到的conda list内容，2.txt是ssh terminal得到的conda list内容。

**Comment by xyxxxxx** [comment]
1. SSH 会话的 login shell 不会继承容器的环境变量，因此其中的环境变量会少很多。一个临时的解决方法是在 SSH 会话中运行命令 `export $(cat /proc/1/environ | tr '\0' '\n' | xargs)`：

```bash
(base) [/t9k/mnt t9kuser@managed-notebook-9ce9c-0]
$env
CONDA_SHLVL=1
CONDA_EXE=/opt/conda/bin/conda
SSH_CONNECTION=10.233.95.172 43982 10.233.95.144 2222
TZ=Asia/Shanghai
CONDA_PREFIX=/opt/conda
...

(base) [/t9k/mnt t9kuser@managed-notebook-9ce9c-0]
$export $(cat /proc/1/environ | tr '\0' '\n' | xargs)
(base) [/t9k/mnt t9kuser@managed-notebook-9ce9c-0]

$env
NV_LIBCUBLAS_DEV_VERSION=11.10.1.25-1
MANAGED_NOTEBOOK_HTTP_9EE3D_PORT_80_TCP_PORT=80
MANAGED_NOTEBOOK_HTTP_6D100_SERVICE_PORT=80
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-7
CONDA_SHLVL=1
...
```

2. 使用 1. 中的方法为 SSH 会话设置相同的环境变量，看看 `conda list` 的结果是否仍不相同。或者给出使用的镜像以及安装 conda 环境的具体步骤，我来尝试复现。

**Comment by shenkejie15** [comment]
本问题已得到解答，关闭 issue。
如果遇到了相同的问题，欢迎打开 issue 继续讨论。
