### ISSUE TITLE
在容器环境中使用 aspera

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#49]
这个 issue 针对如何在容器中使用 [ascp](https://www.ibm.com/products/aspera) 下载数据。

**Comment by ppkube** [comment]
> aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`

这个是客户端场景吧， `-P 33001 ` 是服务器的 SSH service port？所以，如果在容器里运行这个命令，是不需要做任何额外的设置（当前是允许任何 outgoing 的 network traffice）。

所以，实际运行这个命令是出现了什么错误呢？

**Comment by wd0011** [comment]
下载的话，流量应该是ingoing吧。 
具体的报错是：
![image](https://user-images.githubusercontent.com/34251317/232942703-db9d2293-767a-4d2e-bd77-e4036cdc2528.png)

**Comment by ppkube** [comment]
> 下载的话，流量应该是ingoing吧。 
> 
> 具体的报错是：
> 
> ![image](https://user-images.githubusercontent.com/34251317/232942703-db9d2293-767a-4d2e-bd77-e4036cdc2528.png)
> 
> 

由于第一个数据包是从集群里发起的，算做 “出” 集群的 flow

**Comment by ppkube** [comment]
另外，根据 <https://www.ebi.ac.uk/ena/browser/downloading-data> ，也可以使用其它协议下载数据，例如 FTP。t9k 提供的 rclone 很方便: https://t9k.github.io/user-docs/blog/2023/rclone-user-guide.html

**Comment by wd0011** [comment]
> > 下载的话，流量应该是ingoing吧。
> > 具体的报错是：
> > ![image](https://user-images.githubusercontent.com/34251317/232942703-db9d2293-767a-4d2e-bd77-e4036cdc2528.png)
> 
> 由于第一个数据包是从集群里发起的，算做 “出” 集群的 flow

udp不建立连接的话，应该是算进集群的吧？

**Comment by ppkube** [comment]
> > > 下载的话，流量应该是ingoing吧。
> > > 具体的报错是：
> > > ![image](https://user-images.githubusercontent.com/34251317/232942703-db9d2293-767a-4d2e-bd77-e4036cdc2528.png)
> > 
> > 
> > 由于第一个数据包是从集群里发起的，算做 “出” 集群的 flow
> 
> udp不建立连接的话，应该是算进集群的吧？

网络流量的统计来看，主要是下载流量（ingress/inbound）。但是这里考虑的是这个下载 session 的协议本身：session 是从 cluster 内部发起的，从网络管理角度，这个是 egress network traffic。 如果需要设定 K8s network policies 对 network traffic 管理，我们应当制定相应的 egress type 的 rules [1].

[1] https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by wd0011** [comment]
> aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`

这个命令报错的问题，能解决吗？我们同学在催了

**Comment by ppkube** [comment]
> > aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`
> 
> 
> 
> 这个命令报错的问题，能解决吗？我们同学在催了

我们没有 ascp 这个工具 （不能免费下载？）。让同学们用其它协议下载？那个服务是支持多个协议的...

**Comment by wd0011** [comment]
> > > aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`
> > 
> > 
> > 这个命令报错的问题，能解决吗？我们同学在催了
> 
> 我们没有 ascp 这个工具 （不能免费下载？）。让同学们用其它协议下载？那个服务是支持多个协议的...
生物学数据就是用aspera下载的。ascp就是免费让用的。

**Comment by ppkube** [comment]
> > > > aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`
> > > 
> > > 
> > > 这个命令报错的问题，能解决吗？我们同学在催了
> > 
> > 
> > 我们没有 ascp 这个工具 （不能免费下载？）。让同学们用其它协议下载？那个服务是支持多个协议的...
> 生物学数据就是用aspera下载的。ascp就是免费让用的。

着急的话，先用 ftp 协议下载？

 https://www.ebi.ac.uk/ena/browser/downloading-data

**Comment by wd0011** [comment]
> > > > > aspera使用命令如下： `#nohup ascp -i /root/anaconda3/etc/asperaweb_id_dsa.openssh -l 400m -v -P 33001 -k1 -QT era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz ./ >output2 2>&1 &`
> > > > 
> > > > 
> > > > 这个命令报错的问题，能解决吗？我们同学在催了
> > > 
> > > 
> > > 我们没有 ascp 这个工具 （不能免费下载？）。让同学们用其它协议下载？那个服务是支持多个协议的...
> > > 生物学数据就是用aspera下载的。ascp就是免费让用的。
> 
> 着急的话，先用 ftp 协议下载？
> 
> https://www.ebi.ac.uk/ena/browser/downloading-data

ftp几百k到1m的速度。aspera的速度是5-6m。总数据量是100T左右。肯定是优先aspera下载的。端口的问题，就那么难解决吗？

**Comment by ppkube** [comment]
> > 着急的话，先用 ftp 协议下载？
> > https://www.ebi.ac.uk/ena/browser/downloading-data
> 
> ftp几百k到1m的速度。aspera的速度是5-6m。总数据量是100T左右。肯定是优先aspera下载的。端口的问题，就那么难解决吗？

用 rclone 的 ftp 试试，也许速度没那么差。因为，有很多方式可以加速 long latency connection 的下载， 也许 rclone 做的不错。我们下载数据集，rclone 50+Mb 速度 across pacific ...

同时，我们搞到 ascp 之后也诊断一下问题

**Comment by shenkejie15** [comment]
# 总览

经过测试和调研，有以下结论：

* 通常配置下，rclone 下载速度较慢（rclone 测试）。
* 不建议，但是可以通过在物理节点上配置 iptables 来保障 ascp 顺利下载（设置端口）。
* 建议的配置方案（配置方案）。


## rclone 测试

在 rclone 配置文件中添加以下内容：

``` YAML
[ebi]
type = ftp
host = ftp.sra.ebi.ac.uk
user = anonymous
pass = 0OVrrAV5eX57n4uaJ-wF695xxwJrva8ERqh5vkAd
```

使用 rclone 下载可以获得平均不到 1MB/s 的传输速度，增加 transfers 的数量并不能加快下载速度。下面是使用 16 个 transfers 下载时得到的一个较快的速度：

``` shell
$rclone copy -P ebi:vol1/ ./ --transfers=16
Transferred:       99.015 MiB / 203.471 GiB, 0%, 1.247 MiB/s, ETA 1d22h24m
Transferred:            1 / 22, 5%
Elapsed time:      1m40.0s
Transferring:
 *  ERZ017/ERZ017093/ERX200396_accepted_hits.bam:  2% /2.963Gi, 710.185Ki/s, 1h11m14s
 *  ERZ017/ERZ017094/ERX200392_accepted_hits.bam:  0% /4.355Gi, 0/s, -
 * ERZ018/ERZ018629/IRCH-…_coverage.20130824.bam:  0% /32.750Gi, 0/s, -
 *  ERZ017/ERZ017095/ERX200393_accepted_hits.bam:  0% /4.642Gi, 0/s, -
 * ERZ018/ERZ018630/IRCH-…_coverage.20130824.bam:  0% /25.145Gi, 0/s, -
 * ERZ020/ERZ020210/IROO.…ARv3_1.20140307.map.gz: transferring
 * ERZ020/ERZ020210/IROO.…ARv3_1.20140307.ped.gz: transferring
 * ERZ020/ERZ020210/IROO.…ARv3_1.20140307.vcf.gz: transferring
 * ERZ020/ERZ020210/IROO.…_1.20140307.vcf.gz.tbi: transferring
 * ERZ019/ERZ019215/MOCH-…_coverage.20130824.bam:  0% /39.305Gi, 57/s, 204224h26m22s
 * ERZ019/ERZ019215/MOCH-…erage.20130824.bam.bai: transferring
 * ERZ038/ERZ038090/ISGC.…ARv3_1.20140131.map.gz:  0% /250.591Mi, 0/s, -
 * ERZ038/ERZ038090/ISGC.…ARv3_1.20140131.ped.gz:  1% /1.915Gi, 552.664Ki/s, 59m44s
 * ERZ038/ERZ038090/ISGC.…ARv3_1.20140131.vcf.gz:  0% /5.469Gi, 0/s, -
 * ERZ022/ERZ022000/vcfBe…2892-200-37-ASM.vcf.gz: transferring
 * ERZ022/ERZ022000/vcfBe…-200-37-ASM.vcf.gz.tbi: transferring
```

## 设置端口

医学所环境中运行 ascp，得到以下输出：

```shell
$ ascp -i /t9k/mnt/.conda/envs/aspera/etc/asperaweb_id_dsa.openssh -P 33001 -DDD  -l 400m -v -k1  era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz  ./

Session Stop  (Error: Client unable to connect to server (check UDP port and firewall))
```

[aspera 官方支持文档](https://www.ibm.com/support/pages/errors-15-and-1112-udp-ports) 中提到了修改 iptables 的解决方案。

尽管 Docker 容器中并不支持直接修改 iptables，但是作为一种解决办法，我们可以[在 Docker 的规则之前添加 iptables 策略](https://docs.docker.com/network/iptables/#add-iptables-policies-before-dockers-rules)。需要对集群内的所有物理节点运行：

``` shell
sudo iptables -I DOCKER-USER -p udp --dport 33001 -j ACCEPT
```

修改后的测试结果（下载过程中最高速度超过 300Mb/s）：

``` shell
$ ascp -i /t9k/mnt/.conda/envs/aspera/etc/asperaweb_id_dsa.openssh -P 33001 -DDD  -l 400m -v -k1  era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR030/ERR030856/ERR030856.fastq.gz  ./
ERR030856.fastq.gz                                        100% 5384MB 27.5Mb/s    02:30    
Completed: 3272225K bytes transferred in 150 seconds
 (177689K bits/sec), in 1 file.
```

## 配置方案

较为推荐的配置方案是在创建 Notebook 时，在 `.spec.template.spec.containers` 字段中添加以下内容：

``` YAML
          ports:
          - containerPort: 33001
            name: aspera
            protocol: UDP
```

比如下面的 YAML：

``` YAML
apiVersion: tensorstack.dev/v1beta1
kind: Notebook
metadata:
  name: sample
spec:
  type: jupyter
  template:
    spec:
      containers:
        - name: notebook
+         ports:
+           - containerPort: 33001
+             name: aspera
+             protocol: UDP
          image: >-
            registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/tensorflow-2.12.0-notebook-cpu:1.72.0
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - name: workingdir
              mountPath: /t9k/mnt
      volumes:
        - name: workingdir
          persistentVolumeClaim:
            claimName: ''
```

经测试，可以正常使用 ascp 命令下载文件。

**Comment by shenkejie15** [comment]
问题已经得到解决，所以关闭 issue。
如果还有后续问题或讨论，可以随时再打开 issue 进行讨论。
