### ISSUE TITLE
资源限制与notebook创建异常

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#50]
**bug 描述**
资源超出上限后，仍然可以创建新的notebook（用户界面）。
![img_v2_74a9c6f3-9152-4cc1-ab87-ff0188fb2f1g](https://user-images.githubusercontent.com/34251317/232991732-7f7e20c1-b433-47ff-b253-a311f84dc93d.jpg)
但是无法进入notebook。
![img_v2_f988d37b-5259-49e4-875f-4c51ade7e93g](https://user-images.githubusercontent.com/34251317/232991649-ee01518e-6bc6-4fcd-99dd-7fb26639ab33.jpg)
管理员界面中，无法看到新的notebook。（推测没有被创建）

**复现方法**
复现 bug 的步骤：
限制项目资源后，创建超出资源限制的notebook。

**期望的行为（可选）**
优化资源受限时的系统行为，让用户在创建超出限制的notebook时无法进行创建，并明确进行报错。
Improvement：项目内的用户需要能够看到资源限制的图形界面。

**Comment by tswangdi** [comment]
这里的解决方式是：

![WechatIMG2100](https://user-images.githubusercontent.com/42463886/233247017-13025206-da31-4f4f-90d5-28ca917b36e1.jpeg)

在 notebook 列表可以看见错误信息。

**Comment by tswangdi** [comment]
Build Console UI 会将 Notebook 及其子资源的错误显示在图标这里。

这个 issue 所示 bug 的产生是由于 Notebook 控制器没有抓取到子资源 Statefulset 的这种 **Pod 创建失败**的情况。将这种情况补上后就可以了。

**Comment by shenkejie15** [comment]
> 这里的解决方式是：
> 
> ![WechatIMG2100](https://user-images.githubusercontent.com/42463886/233247017-13025206-da31-4f4f-90d5-28ca917b36e1.jpeg)
> 
> 在 notebook 列表可以看见错误信息。
> 
> 下一次发布更新这个内容

已经部署这个更新。

**Comment by tswangdi** [comment]
issue 关闭。

如果还有其他问题，可以再打开该 issue。
