### ISSUE TITLE
PVC 扩容产生的 NodeExpandVolume failed 事件

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#55]
**改进内容**
在 PVC 扩容后，但是集群中反复出现事件：

``` shell
NodeExpandVolume.NodeExpandVolume failed for volume "pvc-e6ee3c83-cda9-4781-afc8-1efb3d42a018" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/cephfs.csi.ceph.com to not support node expansion
```
![image](https://github.com/t9k/user-support/assets/48315992/6d91f4c0-e6ef-4817-82bc-9315c77a18fd)

PVC 扩容本身是成功的，也可以在集群中正常使用。但是这个事件在 PVC 扩容完成后依然会反复出现。

**期望的效果**

查询事件反复出现的原因，阻止事件多次反复出现。

**Comment by adux6991** [comment]
这是 [k8s 的 bug](https://github.com/ceph/ceph-csi/issues/3929)，至今尚未解决，原因是尽管 ceph-csi 声明了 `RequireNodeExpansion: false`（不需要对 pod 所在的 node 的 file system 的 mount point 进行扩容），k8s 仍然会产生 NodeExapandVolume failed 事件。

work around: cluster admin server 目前是直接从 apiserver 获取 event list，添加一个 filter 过滤掉此类 event 即可

@ppkube 这样是否合适？

**Comment by ppkube** [comment]
> work around: cluster admin server 目前是直接从 apiserver 获取 event list，添加一个 filter 过滤掉此类 event 即可

我们先不要 filter，文档里告诉管理员这个 event 是个 K8s bug，可以忽略。因为：1）node expand 成功了，并没有影响产品功能；2）看起来 K8s 会尽快修好

**Comment by adux6991** [comment]
好的：https://docs.google.com/document/d/1ydYRJT5qMCbOJOXPwtoDHSFbGfCgKDdDlkDQcOYZxIs/edit#heading=h.4ooozgid8dqv

> 我们先不要 filter，文档里告诉管理员这个 event 是个 K8s bug，可以忽略。
