### ISSUE TITLE
Rstudio镜像不匹配

### ISSUE THREAD

**Issue by JoJoTsui** [t9k/user-support#56]
**bug 描述**
Rstudio不同版本镜像并没有对应的环境

**复现方法**
复现 bug 的步骤：
 1. 进入 'rocker-4.2.3-tidyverse:1.72.0-sudo'
 2. 输入 'library(tidyverse)'
 3. 提示不存在

**期望的行为（可选）**
每种tag的Rstudio应该包含其对应的环境。

**环境（可选）**
 - 平台版本：1.72.0
 - 镜像：`registry.ibmc.t9kcloud.cn/dockerhub/t9kpublic/rocker-4.2.3-tidyverse:1.72.0-sudo`
 - …

**额外的上下文信息（可选）**
怀疑是镜像管理时打错了tag导致

**Comment by shenkejie15** [comment]
问题已复现，上传新镜像后我会告知。

**Comment by shenkejie15** [comment]
已更新 1.72.1 版本的 RStudio 镜像。在 Build Console 页面禁用缓存刷新后可以选择。

<img width="854" alt="image" src="https://github.com/t9k/user-support/assets/48315992/3058063a-25d6-4a7f-8c13-579b071dd89d">

图中的 conflict 不影响使用，参考 https://tidyverse.tidyverse.org/reference/tidyverse_conflicts.html

**Comment by shenkejie15** [comment]
问题已解决，关闭 issue。如果还有问题或建议，可以随时重新打开这个 issue。
