### ISSUE TITLE
apt 安装的讨论

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#57]
**改进需求**
有同学反馈apt下载的内容重启镜像之后就消失了，apt下载的路径是不是也能替换到/t9k/mnt/路径下啊？

**改进内容**
需要有更好的方式指导用户，满足用户安装 apt 软件包的需求。

**已有的方案**
用户自行[构建 Notebook 自定义镜像](https://t9k.github.io/user-docs/reference/image/build-notebook-custom-image.html)。
需要用户熟悉 Dockerfile，拥有 harbor 的上传权限。

**Comment by shenkejie15** [comment]
使用 apt 时不能选择安装路径，通常这个路径是由软件包的维护者指定的。通常包括但不限于 /usr/share，/usr/bin，/etc 等路径，强行指定安装路径可能导致更多的问题。

**Comment by ppkube** [comment]
apt 虽然可以选择（例如通过下载 source、编译，或者 apt-get download <pkg>,  然后 dpkg -i --force-not-root --root=/t9k/mnt <pkg>.deb）安装到特定的目录下，但过程复杂，容易出错，并且由于 pvc 是多容器可共享的能力，导致容易出现各种问题。

目前比较稳妥的办法是构建自己的 image。

**Comment by wd0011** [comment]
> 



> **改进需求** 有同学反馈apt下载的内容重启镜像之后就消失了，apt下载的路径是不是也能替换到/t9k/mnt/路径下啊？
> 
> **改进内容** 需要有更好的方式指导用户，满足用户安装 apt 软件包的需求。
> 
> **已有的方案** 用户自行[构建 Notebook 自定义镜像](https://t9k.github.io/user-docs/reference/image/build-notebook-custom-image.html)。 需要用户熟悉 Dockerfile，拥有 harbor 的上传权限。

1. 构建的image，能只给某用户独享吗？
2. 关于harbor的权限，目前通过t9k平台上传镜像的权限是怎么控制的？

**Comment by shenkejie15** [comment]
> 1. 构建的image，能只给某用户独享吗？

可以的，该用户创建自己的私有 harbor 仓库即可。然后该用户使用该镜像创建 custom 类型的 Notebook。
存放于私有仓库的镜像，可以参考 https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ 来使用。

> 2. 关于harbor的权限，目前通过t9k平台上传镜像的权限是怎么控制的？

关于 Harbor 的权限管理，可以参考：https://docs.qq.com/doc/DVGxuRnR1anlPTlJo
关于如何创建 Secret 来保存 Registry 的身份信息，在文档中有说明，可以参考：https://t9k.github.io/user-docs/reference/image/build-image-on-platform.html

**Comment by shenkejie15** [comment]
问题已得到解答，关闭 issue。
如果您遇到了类似的问题或者有进一步的建议，可以随时重新打开这个 issue。
