### ISSUE TITLE
新增支持镜像 CKG: Clinical Knowledge Graph

### ISSUE THREAD

**Issue by JoJoTsui** [t9k/user-support#58]
**功能描述**

准备将项目 https://github.com/MannLabs/CKG 部署在 tensorstack 服务器节点，期望的方式：用户根据自己需求自行启动镜像进行访问及数据分析。

- 镜像拉取命令
  -  `docker pull lx5005/docker-ibmcckg:1.0`
- 镜像启动命令
  - `docker run -d --name ckgapp -p 7474:7474 -p 7687:7687 -p 8090:8090 -p 8050:8050 lx5005/docker-ibmcckg:1.0`
- 镜像外置端口
  - `7474`
  - `7687`
  - `8090`
  - `8050`
- 访问页面
  - http://localhost:8090/ JupyterHub
  - http://localhost:7474/ Neo4j
  - http://localhost:8050/ CKG app

**关联的问题**

无

**期望的效果（可选）**

可以正常使用CKG的功能，目前本地大部分已测试通过并提供了打包镜像。

**参考（可选）**

- https://github.com/MannLabs/CKG
- https://aimcenter.feishu.cn/wiki/wikcnJAZpD14feyQNCT1KNgkgOc

**Comment by shenkejie15** [comment]
# 示例

您可以参考 https://github.com/t9k/user-support/issues/48#issuecomment-1516214875 的方式设置。这个示例中提供了通过 Ingress 暴露服务和通过 Service 直接暴露服务两种方式。

这里以较为简单的 Service 方式为例。您需要创建一个 Pod 来运行镜像，并创建一个 Service 来暴露 Pod 的服务。创建的命令如下：

``` bash
$ kubectl create -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: ckg
  labels:
    app.kubernetes.io/name: ckg
spec:
  containers:
  - name: ckg
    image: lx5005/docker-ibmcckg:1.0
    args:
      - -name ckgapp
    ports:
      - containerPort: 7474
        name: neo4j
      - containerPort: 7687
        name: myport
      - containerPort: 8090
        name: jupyterhub
      - containerPort: 8050
        name: ckg
    resources:
        limits:
            cpu: 16
            memory: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ckg
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ckg
  ports:
  - name: neo4j
    protocol: TCP
    port: 7474
    targetPort: neo4j
  - name: myport
    protocol: TCP
    port: 7687
    targetPort: myport
  - name: jupyterhub
    protocol: TCP
    port: 8090
    targetPort: jupyterhub
  - name: ckg
    protocol: TCP
    port: 8050
    targetPort: ckg
EOF
```

确认 Pod 正常运行：
``` bash
$ kubectl get pod ckg
NAME   READY   STATUS    RESTARTS   AGE
ckg    1/1     Running   0          23s
```

查看 Service 以获得端口信息，以 JupyterHub 服务为例，这里 8090 端口对应的 NodePort 为 30894:
``` bash
$ kubectl get svc ckg
NAME   TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                       AGE
ckg    NodePort   10.233.36.41   <none>        7474:30795/TCP,7687:32451/TCP,8090:30894/TCP,8050:30721/TCP   9m56s
```

在浏览器中使用地址：`<any-host-IP>:30894` 进行访问，即可访问 Pod 提供的 JupyterHub 服务。
