### ISSUE TITLE
job提交表单验证错误

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#59]
**bug 描述**
![image](https://github.com/t9k/user-support/assets/34251317/308eba42-f773-447f-a85f-3aaf54df0d3b)
想要增加共享内存，但是报Volume有关字段不能为空。

**复现方法**
复现 bug 的步骤：
创建job，通过修改yaml文件增加dshm字段作为共享内存。

**期望的行为（可选）**
允许运行job时增加共享内存

**Comment by shenkejie15** [comment]
已复现该问题，稍后会更新镜像来解决这个问题。

**Comment by shenkejie15** [comment]
问题已修复，我会关闭这个 issue。如果仍有相关问题欢迎继续讨论。
