### ISSUE TITLE
程序运行速度慢

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#61]
**改进内容**
程序跑起来特别慢，同一套代码，在单卡3090上运行一个 epoch 只需要15秒，在TensorStack Notebook 中需要1分钟（而且速度不稳定，有时可达4分钟）。

备注：
1. 数据放在个人PVC里。
2. 使用了共享 GPU。

**Comment by tswangdi** [comment]
Deplicate of #75

**Comment by tswangdi** [comment]
Duplicate of #75

**Comment by tswangdi** [comment]
Notebook 使用共享 GPU 时，会因为 GPU 上同时运行多个程序导致计算速度慢，且因为程序数量变化而导致计算速度不稳定。

因此建议，仅使用共享 GPU 执行对计算资源要求低、并且占用时间短的计算任务，比如在 Notebook 上调试代码。如果需要使用较多的 GPU 资源，并且会占用一段时间，推荐使用 nvidia.com/gpu（独占 GPU），不要使用共享 GPU。

Issue 关闭，如果后续有其他相关问题，可重新打开该 Issue。
