### ISSUE TITLE
共享 GPU 使用问题

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#62]
**改进内容**
申请共享 GPU 时，申请到的显卡数与声明的数量总是不符，经常出现申请四张只给三张的情况。

**当前建议的改进方式**
1. 禁止用户申请多于一张共享 GPU
2. 当用户设置了多于一张共享 GPU 时，应当给出明确错误提示
3. 推动用户使用 Job 来进行模型训练等大型任务

**Comment by tswangdi** [comment]
Duplicate of #75

**Comment by quanguachong** [comment]
共享 GPU 只适用于执行计算资源要求低、占用时间短的计算任务。如果你需要更多的 GPU 计算资源，你应该使用独占 GPU，而非申请多个共享 GPU 使用。

我们现在提供的 GPU 共享技术基于 [NVIDIA time-slicing，](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#understanding-time-slicing-gpus)Nvidia 共享 GPU 的分配原理如下：
假设节点 N 上有 4 个 GPU（A B C D），每个 GPU 共享为 5 份。那这个节点上会有 4*5=20 个 nvidia.com/gpu.shared 扩展资源。当用户创建一个 Notebook，声明  nvidia.com/gpu.shared: 4 时，K8s 会随机选择 4 个 nvidia.com/gpu.shared 扩展资源分给 Notebook。可能会有下列情况：
* 情况 1: 分配的 4 个 nvidia.com/gpu.shared 都属于 GPU A。用户在 Notebook 中可以看见一个 GPU，这个 GPU 就是 A。
* 情况 2: 分配的 4 个 nvidia.com/gpu.shared 分别属于 GPU A、B、C、D。用户在 Notebook 中可以看见四个 GPU，分别是 A、B、C、D。
* 情况 3: 分配的 4 个 nvidia.com/gpu.shared，有两个属于 GPU A，一个属于 GPU B，一个属于 GPU C。用户在 Notebook 中可以看见 3 个 GPU，分别是 A、B、C。
……

结论：在工作负载声明 `nvidia.com/gpu.shared: x` 来使用共享 GPU 时，推荐的设置是 x = 1。

**Comment by quanguachong** [comment]
Issue 关闭，如果用户后续仍有疑问，可以重新开启该 Issue。
