### ISSUE TITLE
使用 Notebook 时，突然提示 no healthy upstream。

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#63]
**bug 描述**
使用 Notebook 时，突然提示 `no healthy upstream`。

**Comment by shenkejie15** [comment]
经测试，当 Notebook 的 Pod 被删除/驱逐时，会出现 “server connection error” 的提示：
![image](https://github.com/t9k/user-support/assets/48315992/1e0b7b56-1bba-477b-9aca-41c029c6c2d5)

而当刷新页面后，提示信息变为：“no healthy upstream”：
![image](https://github.com/t9k/user-support/assets/48315992/94f09aa2-9591-4922-bbfb-2f23576e60bb)

所以本问题的原因通常是 Notebook Pod 被删除/驱逐，或者节点 Not Ready 等。

**Comment by shenkejie15** [comment]
在过去的一个月里，可能导致 Pod 被删除/驱逐的原因有以下几点：
1. K8s 集群节点配置问题：部分节点未正确配置 kubelet 的 System Reserve 设置，导致 CPU 使用率达到 100%，负载过高，节点进入 Not Ready 状态。
2. 系统管理员操作：为暂时解决上述问题，系统管理员对节点进行了驱逐操作。
3. kubelet 触发驱逐：节点自身满足了 kubelet 的[驱逐阈值](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-thresholds)条件，导致 kubelet 驱逐 Pod。
4. 节点测试/移除：A101 和 A102 节点在测试或移除节点过程中驱逐了节点上的 Pod。
5. T9k 调度器抢占：T9k 调度器的抢占机制导致的驱逐。

针对以上原因，我们提出以下解决方案：
1. 节点配置：正确配置 System Reserve，防止节点因负载过高进入 Not Ready 状态。本修改预计会在 1 月 7 日进行。
2. 系统管理员操作：同上，避免需要驱逐 Pod 的场景发生。
3. 资源限制：这是设计预期的行为。如果您希望避免此类驱逐，可以将 Notebook 的 Resource Limits 设置为与 Resource Requests 相同。
4. 节点测试/移除：后续新节点将在进行完整测试后再加入集群，以避免类似问题的发生。
5. 优化调度器抢占：这是设计预期的行为。如果您希望避免此类驱逐，可以使用不可被抢占的队列或者高优先级的队列来创建 Notebook，并为 Notebook 设置较高的队列内优先级。

**Comment by ppkube** [comment]
> 5\. 优化调度器抢占：这是设计预期的行为。如果您希望避免此类驱逐，可以使用高优先级的队列来创建 Notebook，并为 Notebook 设置较高的队列内优先级。

我们可以设置策略，规定 1）notebook 不能被抢占（使用不能被抢占的 queue）；2）但可以被暂停

**Comment by tswangdi** [comment]
> 在过去的一个月里，可能导致 Pod 被删除/驱逐的原因有以下几点：
> 
> 1. K8s 集群节点配置问题：部分节点未正确配置 kubelet 的 System Reserve 设置，导致 CPU 使用率达到 100%，负载过高，节点进入 Not Ready 状态。
> 2. 系统管理员操作：为暂时解决上述问题，系统管理员对节点进行了驱逐操作。
> 3. kubelet 触发驱逐：节点自身满足了 kubelet 的[驱逐阈值](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-thresholds)条件，导致 kubelet 驱逐 Pod。
> 4. 节点测试/移除：A101 和 A102 节点在测试或移除节点过程中驱逐了节点上的 Pod。
> 5. T9k 调度器抢占：T9k 调度器的抢占机制导致的驱逐。
> 
> 针对以上原因，我们提出以下解决方案：
> 
> 1. 节点配置：正确配置 System Reserve，防止节点因负载过高进入 Not Ready 状态。本修改预计会在 1 月 7 日进行。
> 2. 系统管理员操作：同上，避免需要驱逐 Pod 的场景发生。
> 3. 资源限制：这是设计预期的行为。如果您希望避免此类驱逐，可以将 Notebook 的 Resource Limits 设置为与 Resource Requests 相同。
> 4. 节点测试/移除：后续新节点将在进行完整测试后再加入集群，以避免类似问题的发生。
> 5. 优化调度器抢占：这是设计预期的行为。如果您希望避免此类驱逐，可以使用不可被抢占的队列或者高优先级的队列来创建 Notebook，并为 Notebook 设置较高的队列内优先级。

“节点配置”问题更新：
目前节点配置的资源总量为机器实际资源总量，但是机器上有其他进程在运行，包括 ceph 等，所以节点实际可使用资源并非机器实际资源总量。
当节点按照配置的资源总量分配资源时可能导致实际申请使用的资源数量超过机器实际资源数量，因此节点进入 NotReady 状态。
上述问题的解决方案是，在设置节点资源总量时，为机器上直接运行的进程预留一部分资源。

其他可能导致 Notebook 出现 upstream not healthy 的原因，管理员可以通过修改配置来实现，这部分我们会提供管理员文档介绍合理的操作方案。
Issue 关闭，如果再次出现 upstream not healthy 的状况，请保留现场并联系我们，我们会针对问题具体分析。
