### ISSUE TITLE
使用 Notebook时，频繁出现“server connection error”错误

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#64]
**bug 描述**
使用notebook时，频繁出现server connection error。

**Comment by shenkejie15** [comment]
经测试，当 Notebook 的 Pod 被删除/驱逐时，会出现 “server connection error” 的提示：
![image](https://github.com/t9k/user-support/assets/48315992/1e0b7b56-1bba-477b-9aca-41c029c6c2d5)

而当刷新页面后，提示信息变为：“no healthy upstream”：
![image](https://github.com/t9k/user-support/assets/48315992/94f09aa2-9591-4922-bbfb-2f23576e60bb)

因此本问题和 https://github.com/t9k/user-support/issues/63 属于同一原因，我们合并到 #63 讨论。

**Comment by shenkejie15** [comment]
Duplicate of #63

**Comment by tswangdi** [comment]
该问题的直接原因是页面向服务器发送请求时发现服务器不可用，其根本原因可能是：

* Notebook 的 Pod 被删除/驱逐，详见 [issue63](https://github.com/t9k/user-support/issues/63)
* 用户的 Notebook 处于 Not Ready 状态
* 用户的 cookie 过期（有效期是一周）

我们已经排除了常见的导致 Notebook 服务不可用的问题，但该问题无法彻底解决。

当该问题发生时，用户可以进行以下检查：

* 刷新页面，确认是否需要重新登录
* 确认 Notebook 是否处于正常运行状态，并通过事件和日志查看错误原因

Issue 关闭，如果用户在后续使用过程中仍然遇到此问题，可以重新开启该 Issue。
