### ISSUE TITLE
Notebook 资源使用限额问题

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#68]
**bug 描述**
Notebook 可用资源与申请资源不符，使用时若程序根据 Notebook Resource Limit 配置使用的资源，会导致资源超限，正在进行的任务会被 kill 掉。

**Comment by tswangdi** [comment]
需要更多细节：

* 正在进行的任务会被 kill 掉，指的是 Notebook 正常运行，但是上面运行的进程挂掉了？
* 按照 Notebook Resource Limit 使用资源的时候，是否考虑到 Notebook 本身使用的资源？
* 在任务被 kill 掉时，当前节点的整体资源使用情况是怎么样的？是不是因为 request 设置比 limit 低，且所有用户都试图使用 limit 设置的资源数量，导致节点资源不足？

**Comment by shenkejie15** [comment]
是的，Notebook 正常运行，但是上面运行的进程挂掉了。本问题更多地出现在 Rstudio 类型的 Notebook 中。

下面是来自用户的说明：
R 的默认行为会调用所有资源。比如用户申请一个 Resource Limit 为 16 CPU 的 Notebook，在 Notebook 中查看 top 或 htop 时显示的是宿主机的可用计算资源（例如 64 CPU），如下图所示：
![image](https://github.com/t9k/user-support/assets/48315992/19bb8c86-ec7c-4758-80a8-46aaddd3a25a)
当 R 程序启动时，R 程序认为有 64 CPU 的资源可用，默认全部调用，然后超过了 Notebook 的 Resource Limit，导致 R 程序进程被 kill。

**Comment by ppkube** [comment]
需要看看被 killed 时 os 给的原因。 memory 超限被杀(oom killed)可能性大. 可通过管理员在物理 node 上运行 journactl 查看 log。

**Comment by tswangdi** [comment]
如果是内存使用过量的问题，用户应该可以按照 https://stackoverflow.com/a/24475329 中的方式解决

**Comment by tswangdi** [comment]
容器中的进程可以查看当前节点上所有资源，但实际可使用资源数量受 pod 的 resources.limit 限制。

判断该 Issue 为 R 尝试使用节点上所有内存导致的 OOMKILLED 问题，请参考 https://stackoverflow.com/a/24475329 限制进程使用的资源数量。
Issue 关闭，如果仍然无法解决，可以重新开启该 Issue。
