### ISSUE TITLE
No healthy upstream 后，Notebook 的 Terminal 页面无法实时更新

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#70]
**bug 描述**
出现 No healthy upstream 后重新进入 Notebook，终端页面无法实时更新

**Comment by tswangdi** [comment]
No healthy upstream 的产生，一般是 Notebook 服务挂掉了。可能的原因包括资源抢占、资源回收策略等。

这里需要确认问题中的“终端页面无法实时更新”是什么意思，在 Notebook 重启后，期望终端页面更新什么内容？

**Comment by shenkejie15** [comment]
经询问，这里的“终端页面无法实时更新”指的是训练任务不再继续打印损失函数的值：
![image](https://github.com/t9k/user-support/assets/48315992/211bfd35-d1ef-4613-9fd7-53a5035c0f90)

因此，本问题的原因是 Notebook 服务挂掉（No healthy upstream）后训练停止，可以合并到 #63 进行讨论。

**Comment by shenkejie15** [comment]
Duplicate of #63

**Comment by tswangdi** [comment]
判断原因是 Notebook 创建的 Pod 因某种原因被驱逐或删除，在 Notebook 重新创建后，并不会恢复之前其中运行的进程。
该问题需要解决的是 Notebook Pod 被驱逐或删除问题，移至 #63 讨论。
