### ISSUE TITLE
T9k-pf 无故断连

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#71]
**bug 描述**
t9k-pf 无故断连，但是重连没问题

**详细描述**
运行环境：
* win11
* 使用了 VPN

使用的 t9k-pf 命令：
<img width="1439" alt="image" src="https://github.com/t9k/user-support/assets/48315992/73eceb39-7d2a-44f8-9e46-adbd173ca06e">

t9k-pf 提示的错误信息：
<img width="1282" alt="image" src="https://github.com/t9k/user-support/assets/48315992/47d41154-4623-4406-acc1-dec1ddb8c69b">

根据训练进程，确认问题的发生时间约为 1月11日的上午 09:40。

**Comment by tswangdi** [comment]
根据用户提供的信息，判断 Issue 中提到的 t9k-pf 断连与网络状况相关。

t9k-pf 在断连后会自动重连，说明当前产品能合理处理失败情况，无需改进。

Issue 关闭。
