### ISSUE TITLE
Notebook 断连，运行程序被 kill，但 Notebook并未重启

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#73]
**bug 描述**
Notebook 断连，运行程序被 kill，但 Notebook并未重启。

**Comment by tswangdi** [comment]
这里描述需要更清楚一些，比如 Notebook 断连和重启有什么关系？断连但未重启，指的是 Notebook 没有挂掉（重启）但是 ssh 连不上了（断连）？

**Comment by tswangdi** [comment]
判断原因是 Notebook 创建的 Pod 因某种原因被驱逐或删除，在 Notebook 重新创建后，并不会恢复之前其中运行的进程。

该问题需要解决的是 Notebook Pod 被驱逐或删除问题，移至 #63 讨论。

Issue 关闭
