### ISSUE TITLE
运行性能不稳定

### ISSUE THREAD

**Issue by cztianchao** [t9k/user-support#75]
**bug 描述**
同一个程序在不同时间段处理速度差距极大，最差的时候性能无法接受，甚至中断
![image](https://github.com/t9k/user-support/assets/41623939/15c0238b-4f51-4de1-aef1-c5a0d07ddc17)
![image](https://github.com/t9k/user-support/assets/41623939/8967b9fa-ee84-461a-8c63-935ba50a4bb1)

**复现方法**
复现 bug 的步骤：
使用torchrun运行代码

**Comment by shenkejie15** [comment]
感谢反馈，能否提供运行环境的相关信息，比如：
1. 使用 Notebook 还是 Job 运行
2. 使用独立的 GPU 还是共享 GPU
3. 出现问题的 Notebook/Job 的完整 YAML（可以从列表右侧的“更多”或者 “操作”处获取）

**Comment by cztianchao** [comment]
1.使用 Notebook;
2.共享 GPU;
3.
resources:
            limits:
              cpu: '8'
              memory: 64Gi
              nvidia.com/gpu.shared: 4
            requests:
              cpu: '6'
              memory: 31Gi
              nvidia.com/gpu.shared: 4

volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 6144Mi
          name: dshm

**Comment by tswangdi** [comment]
"gpu.shared: 4" 表示使用了 4% 张卡（共享模式就是将卡分成 100 份，大家共用；而且 4% 也可能分到不同的卡上，比如 3% + 1%），这种情况下训练速度可能受到这张卡上其他训练进程的影响（如果没有其他进程在用，或者其他进程处于卸载数据、加载数据这样不需要算力的情况下，则你可以用到的算力会更多，甚至能用整张卡的算力；相反则更少，所以可能出现不稳定）。

所以请测试用 Job 进行训练，看一下独占 GPU 卡训练时有没有出现你说的不稳定和中断的情况，如果仍然出现问题，我们再继续排查其他条件。

另外，还是不建议再共享的 GPU 上进行实际训练，因为算力少、不稳定，所以推荐用使用共享 GPU 的 Notebook 来调试 GPU 训练代码，进行大规模训练还是用 Job 体验会更好

**Comment by quanguachong** [comment]
我们现在提供的 GPU 共享技术是基于 [NVIDIA time-slicing](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#understanding-time-slicing-gpus)，他有下列两个缺陷，会导致运行性能不稳定：
1. NVIDIA time-slicing 允许多个进程共享一个 GPU，但无法保证每个进程占用的显存大小。如果你选择使用共享 GPU，GPU 上的显存被别的进程占据大多时，会导致你的程序运行性能差。
2. NVIDIA time-slicing 让多个 Notebook 共享同一个 GPU 时，GPU 不是根据 Notebook 数量来平分计算资源的，而是根据所有 Notebook 中使用 GPU 的进程总量来平分计算资源。所以可能会出现下列情况：只有两个 Notebook a 和 b 共享同一个 GPU，但是 b 中有 10 个进程使用 GPU，a 中有 1 个进程使用 GPU。这导致 Notebook a 只能使用 GPU 的 1/11 的计算资源。

建议：共享 GPU 适用于对计算资源要求低、并且占用时间短的计算任务。如果你需要使用较多的 GPU 资源，并且会占用一段时间，推荐创建其他类型的工作负载（如：T9k Job），使用 nvidia.com/gpu，不要使用共享 GPU。

**Comment by tswangdi** [comment]
结论：建议仅使用共享 GPU 执行计算资源要求低、并且占用时间短的计算任务。如果需要使用较多的 GPU 资源，并且会占用一段时间，推荐使用 nvidia.com/gpu（独占 GPU），不要使用共享 GPU。

Issue 关闭，如果有其他相关问题，可以重新开启该 Issue。
