### ISSUE TITLE
Grafana的node监控中，增加gpu使用情况看板

### ISSUE THREAD

**Issue by wd0011** [t9k/user-support#77]
**改进内容**
目前在Grafana中的node监控看板下无法查看到节点的gpu使用情况。

**关联的问题**
无法对集群整体资源使用情况有一个很好的了解，不便于分析集群使用情况。

**期望的效果（可选）**
在node监控下有类似的界面。
![image](https://github.com/t9k/user-support/assets/34251317/07de3ec4-9710-4605-85b2-114bc990d1c3)

可参考教程：
https://zhuanlan.zhihu.com/p/544321724
https://blog.csdn.net/boxrice007/article/details/124802310

**Comment by quanguachong** [comment]
目前产品已经自动部署的 Grafana 系统中，有两个 dashboard 可以查看节点的 GPU 使用情况：
1. dashboard 在 grafana 的路径是 T9k/NVIDIA DCGM Exporter Dashboard
2. dashboard 在 grafana 的路径是 T9k/ “Cluster / Computing Resource / Overview”

Dashboard 1 内容如下图所示，可以选择特定的 node 进行观察：
![Screen Shot 2024-01-19 at 6 00 24 PM](https://github.com/t9k/user-support/assets/24369013/b4b3490e-cc2e-4a69-a277-7484044bdae4)

Dashboard 2 内容入下图所示，可以展示整个集群的 GPU 使用情况：
![Screen Shot 2024-01-19 at 6 53 35 PM](https://github.com/t9k/user-support/assets/24369013/354b2d3a-cb91-4723-b162-2d2a48d30b21)


如果这个两个 dashboard 不够用的话，请提进一步的需求。

**Comment by wd0011** [comment]
> 目前产品已经自动部署的 Grafana 系统中，有两个 dashboard 可以查看节点的 GPU 使用情况：
> 
> 1. dashboard 在 grafana 的路径是 T9k/NVIDIA DCGM Exporter Dashboard
> 2. dashboard 在 grafana 的路径是 T9k/ “Cluster / Computing Resource / Overview”
> 
> Dashboard 1 内容如下图所示，可以选择特定的 node 进行观察： ![Screen Shot 2024-01-19 at 6 00 24 PM](https://private-user-images.githubusercontent.com/24369013/298049454-b4b3490e-cc2e-4a69-a277-7484044bdae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTgzNzEsIm5iZiI6MTcwNTk5ODA3MSwicGF0aCI6Ii8yNDM2OTAxMy8yOTgwNDk0NTQtYjRiMzQ5MGUtY2MyZS00YTY5LWEyNzctNzQ4NDA0NGJkYWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA4MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZWZiZDk1ZDA0YmY1YzQ5YjY1OTA1ZTVlYzY0OTE0YTk3NWZjZjdjZDBmZjY4NzY5Mjg1NjlhMzY1N2M5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z00-EVt-WLJQIwBEMlVooJyj35LNo0zJ4-QLaFMYvqM)
> 
> Dashboard 2 内容入下图所示，可以展示整个集群的 GPU 使用情况： ![Screen Shot 2024-01-19 at 6 53 35 PM](https://private-user-images.githubusercontent.com/24369013/298049774-354b2d3a-cb91-4723-b162-2d2a48d30b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTgzNzEsIm5iZiI6MTcwNTk5ODA3MSwicGF0aCI6Ii8yNDM2OTAxMy8yOTgwNDk3NzQtMzU0YjJkM2EtY2I5MS00NzIzLWIxNjItMmQyYTQ4ZDMwYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA4MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NzI3ZTJkNTk2NDk3YjFkZWQ4YTY1NTZkMWU5ZWIzMzA1Mjc3NjFlMTY0OTc2NjdhYWE0M2I1NmU4OGUxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nprUNW-L8sZxwJdvj1oTKp1RAYTGXotUJboHsXwh7Zs)
> 
> 如果这个两个 dashboard 不够用的话，请提进一步的需求。

这里提到的t9k的资源并不存在

**Comment by tswangdi** [comment]
“t9k 的资源”指的是什么？是指 T9k/NVIDIA DCGM Exporter Dashboard 和 T9k/ “Cluster / Computing Resource / Overview” 这两个 Dashboard 么？

如果是的话，这两个 Dashboard 可以通过以下方式找到：

<img width="900" alt="Screen Shot 2024-01-23 at 17 46 20" src="https://github.com/t9k/user-support/assets/42463886/8655b7ef-16bf-4773-b40a-6797863a402f">

如果你指的是其他指标类型，可以提供具体期望的指标有哪些，我们后续加进去

**Comment by wd0011** [comment]
> “t9k 的资源”指的是什么？是指 T9k/NVIDIA DCGM Exporter Dashboard 和 T9k/ “Cluster / Computing Resource / Overview” 这两个 Dashboard 么？
> 
> 如果是的话，这两个 Dashboard 可以通过以下方式找到：
> 
> <img alt="Screen Shot 2024-01-23 at 17 46 20" width="900" src="https://private-user-images.githubusercontent.com/42463886/298888294-8655b7ef-16bf-4773-b40a-6797863a402f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTU2OTYsIm5iZiI6MTcwNjI1NTM5NiwicGF0aCI6Ii80MjQ2Mzg4Ni8yOTg4ODgyOTQtODY1NWI3ZWYtMTZiZi00NzczLWI0MGEtNjc5Nzg2M2E0MDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3NDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjkxZmQ0ZjExNmI3MjJiNGNjOTZiNjZiMWVkMjc5NzQ2ZTNjMjg0NzJlZGM0MGE2YTUyMzJkOTQxZmQ1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sfpxlCYjufht9p64e-Ml5PSWmofskYg-gLtWOd6BywI">
> 如果你指的是其他指标类型，可以提供具体期望的指标有哪些，我们后续加进去

就是没有这个资源，找不到这个指标

**Comment by quanguachong** [comment]
产品升级产生了一些 bug，导致指标数据无法正常显示。经修复，现在的 Dashboard 页面可以正常查看到相关的监控指标数据了：

![Screen Shot 2024-01-31 at 3 10 06 PM](https://github.com/t9k/user-support/assets/24369013/9f5cb642-9a0d-43e7-9871-3a952119d340)

Issue 关闭，如果后续有其他相关问题，可重新打开该 Issue。
