### ISSUE TITLE
t9k-pf 端口转发报错 i/o timeout

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#78]
**bug 描述**

使用 t9k-pf 过程中，报错 i/o timeout：

![output](https://github.com/t9k/user-support/assets/48315992/69ad8177-08ab-47cd-8efc-ed659b6cf8ec)

暂不知道该问题的触发条件，以下情况均发生过：

1. 刚运行 t9k-pf 时就报错
2. 运行 t9k-pf 过程中突然报错。

**复现方法**
目前没有稳定复现的方法。

**环境**
t9k-pf 版本：0.2.5
t9k-pf 运行环境：个人电脑
VPN 配置：电脑上配置了 VPN ，使用 Clash 作为代理客户端

**Comment by tswangdi** [comment]
根据 Issue 提供的图片，判断问题原因是 t9k-pf 试图访问 home.ibmc.t9kcloud.cn 时出现本地 DNS 解析错误，可能的原因与具体运行环境相关，例如本地运行有 VPN 等。推荐用以下方式检查网络环境：

1. 在本地运行以下命令，并将输出贴到这里：
```bash
dig home.ibmc.t9kcloud.cn
```
2. 确认电脑上是否运行有网络代理软件，将具体细节告知我们。

该 Issue 与产品无关，Issue 关闭。

如果还需要提供支持，再打开 Issue。
