### ISSUE TITLE
Notebook 中如何解压大文件

### ISSUE THREAD

**Issue by shenkejie15** [t9k/user-support#81]
**bug 描述**
在 Notebook 中解压大文件（压缩后超过 200G，原文件约 2T，例如 [https://storage.googleapis.com/alphafold-databases/casp14_versions/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz]）时，显示以下信息：

![img_v3_029i_36505b3c-e295-4f15-838e-ec1228e743fg](https://github.com/t9k/user-support/assets/48315992/5585dee4-3856-408e-b93a-f416f67aaaec)

解压进程会卡在这里，且导致 Notebook 内存资源占用到上限：
![img_v3_029i_db4b935a-a339-43fe-b770-04f1ab96274g](https://github.com/t9k/user-support/assets/48315992/f524d2c2-02d2-4707-9542-51f2212c9c92)

运行最后的报错：
<img width="637" alt="img_v3_029v_534ac05d-0d37-4e3d-909a-2a331ae7fe6g" src="https://github.com/t9k/user-support/assets/48315992/1dfff1ca-f43d-46a1-8eb9-8420089856f4">

**复现方法**
复现 bug 的步骤：
 1. 创建一个绑定的 PVC 存储空间 5Ti 的 Notebook，进入 Notebook
 2. 下载[压缩包](https://storage.googleapis.com/alphafold-databases/casp14_versions/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz)，在 demo 项目的 Notebook “bigfile” 中已经下载了该压缩包
 3. 运行解压命令 tar -zxvf bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
 4. 解压过程中，主要的资源瓶颈是内存：
![image](https://github.com/t9k/user-support/assets/48315992/58fc4fbc-9092-4cce-bb51-efe14c6810a2)
 5. 出现 “Wrote only 4608 of 10240 bytes” 提示信息，tar 进程运行很长时间（超过 2 小时）没有结束：
![image](https://github.com/t9k/user-support/assets/48315992/1cc80d32-1399-4d3d-bc67-3d4679134c22)
6. 运行结束后的报错：
![image](https://github.com/t9k/user-support/assets/48315992/5a6c1494-51b5-47da-826a-b5c3967066ac)
7. 上述运行结束后， Notebook 显示的内存使用依然维持在上限：
![image](https://github.com/t9k/user-support/assets/48315992/aae79e53-3caf-482a-b061-e64176294f3f)

**其他信息**
Wrote only 4608 of 10240 bytes 可以搜索到的错误原因之一是硬盘空间不足，例如：[https://github.com/microsoft/azure-pipelines-tasks/issues/12784]。但这里检查 PVC 大小，5Ti 是充足的：
![image](https://github.com/t9k/user-support/assets/48315992/d15aabb0-75fe-438a-a4be-52950536ea12)

解压后文件大小约为 2T 的信息来源：https://blog.csdn.net/qq_33953882/article/details/118785674

Notebook Pod 的错误日志：
``` bash
[W 2024-04-15 13:14:53.602 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-04-15 13:14:53.837 ServerApp] 500 GET /t9k/notebooks/projects/demo/name/bigfile/lab/api/workspaces/default?1713158093733 (127.0.0.1): Expecting value: line 1 column 1 (char 0)
[W 2024-04-15 13:14:53.837 LabApp] wrote error: 'Expecting value: line 1 column 1 (char 0)'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab_server/workspaces_handler.py", line 201, in get
        workspace = self.manager.load(space_name)
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab_server/workspaces_handler.py", line 128, in load
        return _load_with_file_times(workspace_path)
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab_server/workspaces_handler.py", line 55, in _load_with_file_times
        workspace = json.load(fid)
      File "/opt/conda/lib/python3.10/json/__init__.py", line 293, in load
        return loads(fp.read(),
      File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/jupyterlab_server/workspaces_handler.py", line 204, in get
        raise web.HTTPError(500, str(e)) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Expecting value: line 1 column 1 (char 0))
[E 2024-04-15 13:14:53.841 LabApp] {
      "Host": "home.ibmc.t9kcloud.cn",
      "Accept": "*/*",
      "Referer": "https://home.ibmc.t9kcloud.cn/t9k/notebooks/projects/demo/name/bigfile/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0"
    }
[E 2024-04-15 13:14:53.841 LabApp] 500 GET /t9k/notebooks/projects/demo/name/bigfile/lab/api/workspaces/default?1713158093733 (c099d154907c4e0895d3f8562a3728fa@127.0.0.1) 8.41ms referer=https://home.ibmc.t9kcloud.cn/t9k/notebooks/projects/demo/name/bigfile/lab
```

**期望的行为（可选）**
在一定时间内完成解压工作。

**Comment by adux6991** [comment]
根据 [ceph 文档](https://docs.ceph.com/en/quincy/cephfs/administration/#settings)，cephfs 支持的最大文件大小默认为 1T，已通过以下命令调整为 4T：

```bash
sudo ceph fs set k8s max_file_size 4398046511104
```

**Comment by shenkejie15** [comment]
修改 Ceph 配置后，可以正常解压该文件：
![GmCpWrwr2X](https://github.com/t9k/user-support/assets/48315992/959d6c23-b7a0-4862-a16b-e376d251bacf)

问题已经解决，关闭 issue。
